site_name: UBELIX User Guide
repo_name: 'hpc-unibe-ch/hpc-docs'
repo_url: 'https://github.com/hpc-unibe-ch/hpc-unibe-ch.github.io'
edit_uri: 'edit/main/docs'
site_description: >-
  Instructions, user guides and tutorials for the use of UBELIX, the HPC cluster of the University of Bern.
copyright: The "UBELIX User Guide" is licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> by University of Bern, IT Service Office.<br> It is adapted from the <a href="https://github.com/Lumi-supercomputer/lumi-userguide">LUMI Documentation</a>, used under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.
nav:
  - First steps:
      - Get Started: firststeps/index.md
      - Access to UBELIX: firststeps/accessUBELIX.md
      - Logging in (with SSH client): firststeps/loggingin.md
      - Logging in (with web interface): firststeps/loggingin-webui.md
      - Setting up SSH key pair: firststeps/SSH-keys.md
      - Moving data to/from UBELIX: firststeps/movingdata.md
      - Next steps: firststeps/nextsteps.md
  - Hardware:
      - Overview: hardware/index.md
      - GPU nodes - LUMI-G: hardware/lumig.md
      - CPU nodes - LUMI-C: hardware/lumic.md
      - Data analytics nodes - LUMI-D: hardware/lumid.md
      - Network and interconnect: hardware/network.md
  - Run jobs:
      - Overview: runjobs/index.md
      - Web interface:
          - Introduction: runjobs/webui/index.md
          - Interactive applications:
              - Overview: runjobs/webui/interactive-apps.md
              - Desktop: runjobs/webui/desktop.md
              - Julia-Jupyter: runjobs/webui/julia-jupyter.md
              - Jupyter: runjobs/webui/jupyter.md
              - Jupyter for courses: runjobs/webui/jupyter-for-courses.md
              - TensorBoard: runjobs/webui/tensorboard.md
              - Visual Studio Code: runjobs/webui/vscode.md
          - LUMI environment:
              - Module environment: runjobs/lumi_env/Lmod_modules.md
              - Software stacks: runjobs/lumi_env/softwarestacks.md
              - Daily management: runjobs/lumi_env/dailymanagement.md
              - Data storage options: storage/index.md
              - Billing policy: runjobs/lumi_env/billing.md
          - Batch jobs:
              - Slurm quickstart: runjobs/scheduled-jobs/slurm-quickstart.md
              - Slurm partitions: runjobs/scheduled-jobs/partitions.md
              - Batch jobs: runjobs/scheduled-jobs/batch-job.md
              - Full machine runs: runjobs/scheduled-jobs/hero-runs.md
              - GPU examples: runjobs/scheduled-jobs/lumig-job.md
              - CPU examples: runjobs/scheduled-jobs/lumic-job.md
              - Distribution and binding: runjobs/scheduled-jobs/distribution-binding.md
              - Job array: runjobs/scheduled-jobs/throughput.md
              - Interactive jobs: runjobs/scheduled-jobs/interactive.md
              - Container jobs: runjobs/scheduled-jobs/container-jobs.md
              - Julia scheduled jobs: runjobs/scheduled-jobs/julia.md
  - Software:
      - Overview: software/index.md
      - Install policy: software/policy.md
      - Installing software:
          - EasyBuild: software/installing/easybuild.md
          - Spack: software/installing/spack.md
          - Python packages: software/installing/python.md
          - LUMI container wrapper: software/installing/container-wrapper.md
      - Containers:
          - Singularity/Apptainer: software/containers/singularity.md
      - Software guides:
          - Software library: https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/
          - CP2K: https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/c/CP2K/
          - PyTorch: https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/p/PyTorch/
          - ParaView: https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/p/ParaView
          - QuantumESPRESSO: https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/q/QuantumESPRESSO/
          - VASP: https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/v/VASP/
      - Local software collections:
          - CSC: software/local/csc.md
  - Developing:
      - Overview: development/index.md
      - Compiling:
          - Programming environment: development/compiling/prgenv.md
          - Cray compilers: development/compiling/cce.md
          - GNU compilers: development/compiling/gnu.md
      - High performance libraries:
          - Cray libraries: development/libraries/cray-libraries.md
      - Optimizing for LUMI:
          - Using hugepages: development/optimizing/hugepages.md
      - Debugging:
          - Parallel debugging: development/debugging/gdb4hpc.md
          - Memory debugging: development/debugging/valgrind4hpc.md
          - Crash or deadlock: development/debugging/stat-atp.md
      - Performance analysis:
          - Performance analysis strategies: development/profiling/strategies.md
          - Cray Performance Analysis Tool: development/profiling/perftools.md
  - Storage:
      - Overview: storage/index.md
      - Quota: storage/quota.md
      - Scratch: storage/scratch.md
  - Support:
      - Support: support/index.md
      - Data Science Lab: support/dsl.md
      - Known issues: support/issues.md
      - FAQ: support/faq.md
      - UBELIX service status: https://ubelix.hpc.unibe.ch
  - Code of Conduct: code-of-conduct.md


theme:
  name: material
  #  custom_dir: mkdocs_lumi/

extra_css:
  - 'stylesheets/unibe.css'

plugins:
  - git-revision-date
  - search

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists
  - smarty
  - tables
  - toc

# Social links bottom right
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/hpc-unibe-ch

      #  greetings: Welcome to the LUMI Documentation
      #  custom_dir: mkdocs_lumi/
      #  language: en
      #  features:
      #    # - navigation.instant
      #    - navigation.tabs
      #    - navigation.sections
      #    - search.suggest
      #    - content.code.annotate
      #  
      #    #  palette:
      #    #    scheme: default
      #    #    primary: lumi
      #    #    accent: lumi
      #    #
      #    #  font: false
      #    #  
      #    #  favicon: assets/favicon.png
      #    #
      #    #  icon:
      #    #    logo: logo
      #    #  
      #    #  home_primary:
      #    #    title: Get Started
      #    #    page: firststeps/getstarted/
      #    #  home_secondary:
      #    #    title: To LUMI Main Page
      #    #    page: https://lumi-supercomputer.eu/
      #
      #extra:
      #  social:
      #    - icon: fontawesome/brands/github
      #      link: https://github.com/Lumi-supercomputer/lumi-userguide/
      #    - icon: fontawesome/brands/twitter
      #      link: https://twitter.com/LUMIhpc
      #
      #markdown_extensions:
      #  - toc:
      #      toc_depth: 3
      #      permalink: true
      #      permalink_title: Anchor link to this section for reference
      #  - admonition
      #  - md_in_html
      #  - attr_list
      #  - footnotes
      #  - pymdownx.details
      #  - pymdownx.tabbed:
      #      alternate_style: true
      #  - pymdownx.superfences:
      #      custom_fences:
      #        - name: mermaid
      #          class: mermaid
      #          format: !!python/name:pymdownx.superfences.fence_code_format
      #  - pymdownx.highlight:
      #      anchor_linenums: true
      #  - pymdownx.inlinehilite
      #  - pymdownx.snippets
      #  - pymdownx.keys
      #  - pymdownx.emoji:
      #      emoji_index: !!python/name:material.extensions.emoji.twemoji
      #      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      #
      #plugins:
      #  - redirects:
      #      redirect_maps:
      #        'computing/Lmod_modules.md': 'runjobs/lumi_env/Lmod_modules.md'
      #        'firststeps/getstarted.md': 'firststeps/index.md'
      #        'software/packages/pytorch.md': 'https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/p/PyTorch/'
      #  - search
