site_name: UBELIX User Guide
repo_name: 'hpc-unibe-ch/ubelix-userguide'
repo_url: 'https://github.com/hpc-unibe-ch/ubelix-userguide'
edit_uri: 'edit/main/docs'
site_description: >-
  Instructions, user guides and tutorials for the use of UBELIX, the HPC cluster of the University of Bern.
copyright: The "UBELIX User Guide" is licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> by University of Bern, IT Service Office.<br> It is adapted from the <a href="https://github.com/Lumi-supercomputer/lumi-userguide">LUMI Documentation</a>, used under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.
nav:
  - First steps:
      - Get Started: firststeps/index.md
      - Access to UBELIX: firststeps/accessUBELIX.md
      - Logging in (with SSH client): firststeps/loggingin.md
      - Logging in (with web interface): firststeps/loggingin-webui.md
      - Setting up SSH key pair: firststeps/SSH-keys.md
      - Moving data to/from UBELIX: firststeps/movingdata.md
      - Next steps: firststeps/nextsteps.md
  - Hardware:
      - Overview: hardware/index.md
      - CPU nodes: hardware/cpu.md
      - GPU nodes: hardware/gpu.md
      - Network and interconnect: hardware/network.md
  - Running jobs:
      - Overview: runjobs/index.md
      - Partitions / QoS: slurm/partitions.md
      - Web interface:
          - Introduction: runjobs/ondemand/index.md
          - Interactive applications:
              - Jupyter: runjobs/ondemand/jupyter.md
              - RStudio: runjobs/ondemand/rstudio.md
              - Visual Studio Code: runjobs/ondemand/code-server.md
          - Troubleshooting: runjobs/ondemand/troubleshooting.md
      - Basic batch jobs:
          - Slurm quickstart: runjobs/scheduled-jobs/slurm-quickstart.md
          - Submitting jobs: slurm/submission.md
          - Monitoring Jobs: slurm/monitoring-jobs.md
          - Deleting Jobs: slurm/deleting-jobs.md
          - GPU Jobs: slurm/gpus.md
          - Interactive jobs: runjobs/scheduled-jobs/interactive.md
          - Batch jobs: runjobs/scheduled-jobs/batch-job.md
          - Container jobs: runjobs/scheduled-jobs/container-jobs.md
      - Advanced topics:
          - Job array: runjobs/scheduled-jobs/throughput.md
          - Array Jobs with Slurm: slurm/array-jobs.md
          - Job dependencies: slurm/dependencies.md
          - Investigating a Job Failure: slurm/investigating-job-failure.md
          - Checkpointing: slurm/checkpointing.md
          - Fair Share: slurm/fair-share.md
          - Preemption: runjobs/scheduled-jobs/preemption.md
  - Software:
      - Overview: software/index.md
      - Software environment: software/Lmod_modules.md
      - Installing software:
          - Python packages: software/installing/python.md
          - R packages: software/installing/python.md
          - EasyBuild: software/installing/easybuild.md
          - Containers: software/containers/apptainer.md
      - Software guides:
          - Overview: software/packages/overview.md
          - JupyterLab: software/JupyterLab.md
          - MATLAB: software/matlab.md
          - Parallel BZIP2: software/bzip2.md
          - ParaView: software/ParaView.md
          - R: software/r.md
          - Visual Studio Code: software/VisualStudioCode.md
  - Developing:
      - Overview: development/index.md
      - Compiling:
          - Programming environment: development/compiling/prgenv.md
          - Cray compilers: development/compiling/cce.md
          - GNU compilers: development/compiling/gnu.md
      - Debugging:
          - Parallel debugging: development/debugging/gdb4hpc.md
          - Memory debugging: development/debugging/valgrind4hpc.md
          - Crash or deadlock: development/debugging/stat-atp.md
  - Storage:
      - Overview: storage/index.md
      - Quota: storage/quota.md
      - Scratch: storage/scratch.md
  - Costs and Investments: costs_investments.md
  - Support:
      - Support: support/index.md
      - Data Science Lab: support/dsl.md
      - Known issues: support/issues.md
      - FAQ: support/faq.md
      - UBELIX service status: https://ubelix.hpc.unibe.ch
  - Code of Conduct: code-of-conduct.md


theme:
  name: material
  #  custom_dir: mkdocs_lumi/

extra_css:
  - 'stylesheets/unibe.css'

plugins:
  - git-revision-date
  - search

# See https://python-markdown.github.io/extensions/ and
# See https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#Bundles
#     https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists
  - smarty
  - tables
  - toc

# Social links bottom right
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/hpc-unibe-ch

      #  greetings: Welcome to the LUMI Documentation
      #  custom_dir: mkdocs_lumi/
      #  language: en
      #  features:
      #    # - navigation.instant
      #    - navigation.tabs
      #    - navigation.sections
      #    - search.suggest
      #    - content.code.annotate
      #  
      #    #  palette:
      #    #    scheme: default
      #    #    primary: lumi
      #    #    accent: lumi
      #    #
      #    #  font: false
      #    #  
      #    #  favicon: assets/favicon.png
      #    #
      #    #  icon:
      #    #    logo: logo
      #    #  
      #    #  home_primary:
      #    #    title: Get Started
      #    #    page: firststeps/getstarted/
      #    #  home_secondary:
      #    #    title: To LUMI Main Page
      #    #    page: https://lumi-supercomputer.eu/
      #
      #extra:
      #  social:
      #    - icon: fontawesome/brands/github
      #      link: https://github.com/Lumi-supercomputer/lumi-userguide/
      #    - icon: fontawesome/brands/twitter
      #      link: https://twitter.com/LUMIhpc
      #
      #markdown_extensions:
      #  - toc:
      #      toc_depth: 3
      #      permalink: true
      #      permalink_title: Anchor link to this section for reference
      #  - admonition
      #  - md_in_html
      #  - attr_list
      #  - footnotes
      #  - pymdownx.details
      #  - pymdownx.tabbed:
      #      alternate_style: true
      #  - pymdownx.superfences:
      #      custom_fences:
      #        - name: mermaid
      #          class: mermaid
      #          format: !!python/name:pymdownx.superfences.fence_code_format
      #  - pymdownx.highlight:
      #      anchor_linenums: true
      #  - pymdownx.inlinehilite
      #  - pymdownx.snippets
      #  - pymdownx.keys
      #  - pymdownx.emoji:
      #      emoji_index: !!python/name:material.extensions.emoji.twemoji
      #      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      #
      #plugins:
      #  - redirects:
      #      redirect_maps:
      #        'computing/Lmod_modules.md': 'runjobs/lumi_env/Lmod_modules.md'
      #        'firststeps/getstarted.md': 'firststeps/index.md'
      #        'software/packages/pytorch.md': 'https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/p/PyTorch/'
      #  - search
